#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <assert.h>

#define RECORD_MAGIC_BYTE 123
#define RECORD_MAGIC_SEED 17 

size_t record_size = 128;
double compressibility = 1.0;

/**
 * Determines what the value of a record should
 * be at a given index.
 */
static unsigned char calculate_record_byte(int i)
{
    /* The first record_size / compressibility bytes should be
     * the magic byte, so that a compression algorithm reduces
     * it to 1 / compressibility the size it normally would be.
     * Fill the rest with reproducible garbage that probably
     * won't be compressed very much. */
    unsigned value;

    /* All bytes up to record_size / compressibility should
     * be the magic byte. That way, they are compressed to
     * almost nothing. Otherwise, it should be a number
     * generated by some convoluted forumula that hopefully
     * won't be too compressible. */
    if (i * 1.0 < record_size / compressibility) {
        value = RECORD_MAGIC_BYTE;
    } else {
        value = RECORD_MAGIC_SEED * i + i;
    }

    return value & 0xFF;
}

static void populate_record(void * record)
{
    size_t i;
    unsigned char * cbuf = record;

    for (i = 0; i < record_size; i++) {
        cbuf[i] = calculate_record_byte(i);
        printf("%s: index %lu, value %u\n", 
                __FUNCTION__, i, cbuf[i]);
    }
}

static int verify_record(void * record)
{
    size_t i;
    unsigned char expected;
    unsigned char * cbuf = record;

    for (i = 0; i < record_size; i++) {
        expected = calculate_record_byte(i);
        if (cbuf[i] != expected) {
            fprintf(stderr, "%s: byte %lu got %d wanted %d\n",
                    __FUNCTION__, i, cbuf[i], expected);
        }
    }

    return 0;
}

int main(int argc, char * argv[])
{
    unsigned char * record;

    if (argc != 3) {
        printf("usage: ./compressibility <record_size> <factor>\n");
        return 1;
    }

    compressibility = atof(argv[2]);
    assert(compressibility >= 1.0);

    record_size = atol(argv[1]);
    assert(record_size > 8);
    assert(record_size * 1.0 >= compressibility);

    printf("record size = %lu, compressibility = %lf\n",
            record_size, compressibility);

    record = malloc(record_size);

    populate_record(record);

    verify_record(record);

    free(record);

    return 0;
}
