#!/bin/bash

ROOT_DIR=$HOME/tokufs
MPICH="mpich2-1.3.2p1"
ORIG=$ROOT_DIR/adio-patch/$MPICH.ORIG

if [ ! -e $ORIG ] ; then
	cd $ROOT_DIR/adio-patch/
	tar xf $ROOT_DIR/archives/mpich2-1.3.2p1.tar.gz
	/bin/mv -f mpich2-1.3.2p1 $ORIG
fi

rm -rf $MPICH
/bin/cp -rf $ORIG $MPICH
/bin/cp -rf $ROOT_DIR/src/ad_tokufs	$MPICH/src/mpi/romio/adio
diff -Naur $ORIG $MPICH > $ROOT_DIR/adio-patch/tokufs-mpich2.patch

exit 0
